name: readmore
description: A Flutter package than allow expand and collapse text dynamically Plus
version: 0.0.1
repository: https://github.com/masreplay/readmore

environment:
  sdk: ">=3.1.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
